### ISSUE TITLE
Fix local Mongo connection issues

### ISSUE THREAD

**Issue by FiddlersCode** [FiddlersCode/leopold#44]
Currently, trying to bring up the docker stack locally causes an error with Mongo connection:

```MongoNetworkError: failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
app_1       |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14) {
app_1       |   name: 'MongoNetworkError',
app_1       |   [Symbol(mongoErrorContextSymbol)]: {}
app_1       | }]
app_1       |     at Pool.<anonymous> (/usr/src/app/node_modules/mongodb/lib/core/topologies/server.js:438:11)
app_1       |     at Pool.emit (events.js:210:5)
app_1       |     at Pool.EventEmitter.emit (domain.js:475:20)
app_1       |     at /usr/src/app/node_modules/mongodb/lib/core/connection/pool.js:561:14
app_1       |     at /usr/src/app/node_modules/mongodb/lib/core/connection/pool.js:994:11
app_1       |     at /usr/src/app/node_modules/mongodb/lib/core/connection/connect.js:31:7
app_1       |     at callback (/usr/src/app/node_modules/mongodb/lib/core/connection/connect.js:264:5)
app_1       |     at Socket.<anonymous> (/usr/src/app/node_modules/mongodb/lib/core/connection/connect.js:293:7)
app_1       |     at Object.onceWrapper (events.js:300:26)
app_1       |     at Socket.emit (events.js:210:5) {
app_1       |   name: 'MongoNetworkError',
app_1       |   [Symbol(mongoErrorContextSymbol)]: {}
app_1       | }
```
Need to figure out the cause of this error and fix it.

**Comment by FiddlersCode** [comment]
Simplest solution to change the port?
